language: python
python:
  - "3.5"
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - mv travis_fullchain.pem /ssl/keys/fullchain.pem
  - mv travis_privkey.pem /ssl/keys/privkey.pem
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
