title: Lovelace test
# Include external resources
resources:
  - url: /local/my-custom-card.js
    type: js
  - url: /local/my-webfont.css
    type: css
  - url: /local/custom_ui/weather-card.js
    type: js
  - url: /local/custom_ui/weather-card.css
    type: css
  - url: /local/custom_ui/dark-sky-weather-card.js?v=2
    type: js
  - url: /local/custom_ui/dark-sky-weather-card.css
    type: css

views:

  - title:  Rooms
    id: rooms
    background: center / cover no-repeat url("/local/images/background.jpg") fixed
    theme: darkcyan
    cards:
      - type: glance
        title: Lounge Room
        entities:
          - entity: switch.living_2_6
          - entity: binary_sensor.motion_sensor_158d0001d98554
            name: Motion
          - entity: input_boolean.lounge_pir_enable
            name: Motion (Auto)
            tap_action: toggle
          - entity: sensor.temperature_158d0001ad39a8
          - entity: sensor.humidity_158d0001ad39a8



#
#  - icon: mdi:weather-cloudy
#    background: center / cover no-repeat url("local/images/background.jpg") fixed
#    id: weather
#    title: Weather
#    cards:
#      #yweather
#      - type: "custom:weather-card"
#        entity_weather: weather.yweather
#        entity_sun: sun.sun
#      #darksky weather
#      - type: custom:dark-sky-weather-card
#        entity_sun: sun.sun
#        entity_daily_summary: sensor.dark_sky_daily_summary
#        entity_current_conditions: sensor.dark_sky_icon
#        entity_humidity: sensor.dark_sky_humidity
#        entity_pressure: sensor.dark_sky_pressure
#        entity_temperature: sensor.dark_sky_temperature
#        entity_visibility: sensor.dark_sky_visibility
#        entity_wind_bearing: sensor.dark_sky_wind_bearing
#        entity_wind_speed: sensor.dark_sky_wind_speed
#        entity_forecast_high_temp_1: sensor.dark_sky_daytime_high_temperature_1
#        entity_forecast_high_temp_2: sensor.dark_sky_daytime_high_temperature_2
#        entity_forecast_high_temp_3: sensor.dark_sky_daytime_high_temperature_3
#        entity_forecast_high_temp_4: sensor.dark_sky_daytime_high_temperature_4
#        entity_forecast_high_temp_5: sensor.dark_sky_daytime_high_temperature_5
#        entity_forecast_low_temp_1: sensor.dark_sky_overnight_low_temperature
#        entity_forecast_low_temp_2: sensor.dark_sky_overnight_low_temperature_1
#        entity_forecast_low_temp_3: sensor.dark_sky_overnight_low_temperature_2
#        entity_forecast_low_temp_4: sensor.dark_sky_overnight_low_temperature_3
#        entity_forecast_low_temp_5: sensor.dark_sky_overnight_low_temperature_4
#        entity_forecast_icon_1: sensor.dark_sky_icon_1
#        entity_forecast_icon_2: sensor.dark_sky_icon_2
#        entity_forecast_icon_3: sensor.dark_sky_icon_3
#        entity_forecast_icon_4: sensor.dark_sky_icon_4
#        entity_forecast_icon_5: sensor.dark_sky_icon_5
