- platform: rest
  resource: http://192.168.1.200:8126/container/grafana
  name: Grafana
  icon: mdi:chart-line
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://192.168.1.200:8126/container/nodered
  name: Node-Red
  icon: mdi:home-automation
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
