- platform: nzbget
  host: 192.168.1.10
  username: !secret nzbget_username
  password: !secret nzbget_password
  monitored_variables:
    - article_cache
    - average_download_rate
    - download_rate
    - download_paused
    - download_size
    - free_disk_space
    - post_paused
    - remaining_size
    - uptime
