- platform: modbus
  scan_interval: 10
  registers:
    #Fronius Registers
    #Note! These registers only apply to inverters. These registers are not relevant
    #to Fronius String Controls and energy meters
    - name: Fronius_Site_Power
      unit_of_measurement: W
      slave: 1
      register_type: holding
      register: 499
      count: 2
      data_type: uint
      precision: 0
    - name: Fronius_Site_Energy_Day
      unit_of_measurement: Wh
      slave: 1
      register_type: holding
      register: 501
      count: 4
      data_type: uint
      precision: 0
    - name: Fronius_Site_Energy_Year
      unit_of_measurement: Wh
      slave: 1
      register_type: holding
      register: 505
      count: 4
      data_type: uint
      precision: 0
    - name: Fronius_Site_Energy_Total
      unit_of_measurement: Wh
      slave: 1
      register_type: holding
      register: 509
      count: 4
      data_type: uint
      precision: 0
    #register address map is dependant on setting on inverter either 'float' or 'int+SF'
    #inverter has been set to 'float' so registers below are referencing the 'float' map
    #Common & Inverter Model
    - name: Fronius_Inverter_AC_Current
      unit_of_measurement: A
      slave: 1
      register_type: holding
      register: 40071
      count: 2
      data_type: float
      precision: 2
    - name: Fronius_Inverter_AC_Voltage
      unit_of_measurement: V
      slave: 1
      register_type: holding
      register: 40085
      count: 2
      data_type: float
      precision: 1
    - name: Fronius_Inverter_AC_Frequency
      unit_of_measurement: Hz
      slave: 1
      register_type: holding
      register: 40093
      count: 2
      data_type: float
      precision: 2
    - name: Fronius_Inverter_AC_Apparent_Power
      unit_of_measurement: VA
      slave: 1
      register_type: holding
      register: 40095
      count: 2
      data_type: float
      precision: 0
    - name: Fronius_Inverter_AC_Reactive_Power
      unit_of_measurement: VAr
      slave: 1
      register_type: holding
      register: 40097
      count: 2
      data_type: float
      precision: 0
    - name: Fronius_Inverter_AC_Power_Factor
      unit_of_measurement: PF
      slave: 1
      register_type: holding
      register: 40099
      count: 2
      data_type: float
      precision: 2
      scale: 0.01
    - name: Fronius_Inverter_DC_Total_Power
      unit_of_measurement: W
      slave: 1
      register_type: holding
      register: 40107
      count: 2
      data_type: float
      precision: 2
    - name: Fronius_Inverter_Operating_State
      slave: 1
      register_type: holding
      register: 40118
      count: 1
      data_type: uint
    #Immediate Control Model (IC123)
    - name: Fronius_Inverter_Output_Max_Limit_Pct
      unit_of_measurement: '%'
      slave: 1
      register_type: holding
      register: 40242
      count: 1
      data_type: uint
      precision: 2
      scale: 0.01
    - name: Fronius_Inverter_Output_Max_Limit_Enable
      slave: 1
      register_type: holding
      register: 40246
      count: 1
      data_type: uint
    #Multiple MPPT Inverter Extension Model (I160)
    - name: Fronius_Inverter_DC_Power_Scale_Factor
      slave: 1
      register_type: holding
      register: 40267
      count: 1
      data_type: int
    - name: Fronius_Inverter_DC1_Current
      unit_of_measurement: A
      slave: 1
      register_type: holding
      register: 40282
      count: 1
      data_type: uint
      precision: 2
      scale: 0.01
    - name: Fronius_Inverter_DC1_Voltage
      unit_of_measurement: V
      slave: 1
      register_type: holding
      register: 40283
      count: 1
      data_type: uint
      precision: 2
      scale: 0.01
    - name: Fronius_Inverter_DC1_Power_Raw
      unit_of_measurement: V
      slave: 1
      register_type: holding
      register: 40284
      count: 1
      data_type: uint
    - name: Fronius_Inverter_DC2_Current
      unit_of_measurement: A
      slave: 1
      register_type: holding
      register: 40302
      count: 1
      data_type: uint
      precision: 2
      scale: 0.01
    - name: Fronius_Inverter_DC2_Voltage
      unit_of_measurement: V
      slave: 1
      register_type: holding
      register: 40303
      count: 1
      data_type: uint
      precision: 2
      scale: 0.01
    - name: Fronius_Inverter_DC2_Power_Raw
      unit_of_measurement: W
      slave: 1
      register_type: holding
      register: 40304
      count: 1
      data_type: uint
    #fronius smart meter - slave no is '240'
    - name: Fronius_Meter_Current
      unit_of_measurement: A
      slave: 240
      register_type: holding
      register: 40071
      count: 2
      data_type: float
    - name: Fronius_Meter_Voltage
      unit_of_measurement: V
      slave: 240
      register_type: holding
      register: 40079
      count: 2
      data_type: float
    - name: Fronius_Meter_Frequency
      unit_of_measurement: Hz
      slave: 240
      register_type: holding
      register: 40095
      count: 2
      data_type: float
    - name: Fronius_Meter_Power
      unit_of_measurement: W
      slave: 240
      register_type: holding
      register: 40097
      count: 2
      data_type: float
    - name: Fronius_Meter_Apparent_Power
      unit_of_measurement: VA
      slave: 240
      register_type: holding
      register: 40105
      count: 2
      data_type: float
    - name: Fronius_Meter_Reactive_Power
      unit_of_measurement: VAr
      slave: 240
      register_type: holding
      register: 40114
      count: 2
      data_type: float
    - name: Fronius_Meter_Power_Factor
      unit_of_measurement: PF
      slave: 240
      register_type: holding
      register: 40121
      count: 2
      data_type: float
    - name: Fronius_Meter_Energy_Exported
      unit_of_measurement: Wh
      slave: 240
      register_type: holding
      register: 40129
      count: 2
      data_type: float
    - name: Fronius_Meter_Energy_Imported
      unit_of_measurement: Wh
      slave: 240
      register_type: holding
      register: 40137
      count: 2
      data_type: float
