- platform: rest
  resource: https://api.github.com/repos/potatothesparky/homeassistant/branches
  method: GET
  name: Git Branches
  headers:
    User-Agent: potatothesparky
  json_attributes:
  value_template: '{{ value_json }}'
