#plant_1 - Peace Lilly (Buffet)
- platform: mqtt
  name: plant_1_moisture
  state_topic: "home/garden/plants/plant_1/"
  value_template: '{{ value_json.moisture | int }}'
  unit_of_measurement: '%'
  friendly_name: 'Peace Lilly (Buffet) Moisture'
- platform: mqtt
  name: plant_1_battery
  state_topic: "home/garden/plants/plant_1/"
  value_template: '{{ value_json.battery | int }}'
  unit_of_measurement: '%'
  friendly_name: 'Peace Lilly (Buffet) Battery'
- platform: mqtt
  name: plant_1_temperature
  state_topic: "home/garden/plants/plant_1/"
  value_template: '{{ value_json.temperature | float }}'
  unit_of_measurement: '°C'
  friendly_name: 'Peace Lilly (Buffet) Temperature'
- platform: mqtt
  name: plant_1_conductivity
  state_topic: "home/garden/plants/plant_1/"
  value_template: '{{ value_json.conductivity | int }}'
  unit_of_measurement: 'µS/cm'
  friendly_name: 'Peace Lilly (Buffet) Fertility'
- platform: mqtt
  name: plant_1_brightness
  state_topic: "home/garden/plants/plant_1/"
  value_template: '{{ value_json.brightness | int }}'
  unit_of_measurement: 'Lux'
  friendly_name: 'Peace Lilly (Buffet) Brightness'
