- platform: rest
  resource: !secret solar_resource
  method: GET
  name: Solar Overview
  json_attributes:
    - sid
    - ludt
    - E-Today
    - E-Month
    - E-Total
    - TotalYield
    - CO2Avoided
    - Power
  value_template: '{{ value_json.sid }}'
- platform: template
  sensors:
    solar_energy_today:
      friendly_name: 'Solar Energy Today'
      value_template: '{{states.sensor.solar_overview.attributes["E-Today"].value}}'
      unit_of_measurement: "kWh"
    solar_energy_this_month:
      friendly_name: 'Solar Energy This Month'
      value_template: '{{states.sensor.solar_overview.attributes["E-Month"].value}}'
      unit_of_measurement: "kWh"
    solar_energy_total:
      friendly_name: 'Solar Energy Total'
      value_template: '{{states.sensor.solar_overview.attributes["E-Total"].value}}'
      unit_of_measurement: "kWh"
    solar_power_current:
      friendly_name: 'Solar Power Current'
      value_template: >-
        {% if states.sensor.solar_overview.attributes["Power"].unit == 'W' %}
          {{states.sensor.solar_overview.attributes["Power"].value}}
        {% elif states.sensor.solar_overview.attributes["Power"].unit == 'kW' %}
          {{states.sensor.solar_overview.attributes["Power"].value | float * 1000}}
        {% else %}
          n/a
        {% endif %}
      #'{{states.sensor.solar_overview.attributes["Power"].value}}'
      unit_of_measurement: "W"
    solar_last_update:
      friendly_name: 'Solar Last Update'
      value_template: '{{states.sensor.solar_overview.attributes["ludt"]}}'
