- platform: systemmonitor
  resources:
    - type: disk_use_percent
    - type: memory_use_percent
    - type: swap_use_percent
    - type: load_1m
    - type: load_5m
    - type: processor_use
    - type: since_last_boot