#template sensors to make energy sensors more user readable
- platform: template
  sensors:
    #WIP - still working on this one
#    solar_energy_sunday:
#      friendly_name: "Sunday"
#      icon_template: mdi:solar-power
#      entity_id: input_number.solar_energy_1
#      value_template: >-
#        {% set test=now().weekday() + 1 %}
#        {{test}}
#        {% if test > 7 %}
#          {% set test = test -7 %}
#          {{test}}
#        {% else %}
#          {{test}}
#        {% endif %}
#        {% set var="input_number.solar_energy_" + test|string %}
#        {{var}}
#        {{ now().weekday() }}
#        {{ (states('input_number.solar_energy_ '+ test|string)|float / 1000)|round(2) }}
    fronius_meter_power_kw:
      friendly_name: House
      icon_template: mdi:flash
      entity_id: sensor.fronius_meter_power
      unit_of_measurement: kW
      value_template: >-
        {{ (states('sensor.fronius_meter_power')|float / 1000)|round(2) }}
    fronius_site_energy_day_kwh:
      friendly_name: Solar Generation Today
      icon_template: mdi:flash
      entity_id: sensor.fronius_site_energy_day
      unit_of_measurement: kWh
      value_template: >-
        {{ (states('sensor.fronius_site_energy_day')|float / 1000)|round(2) }}
    fronius_site_power_kw:
      friendly_name: House
      icon_template: mdi:solar-power
      entity_id: sensor.fronius_site_power
      unit_of_measurement: kW
      value_template: >-
        {{ (states('sensor.fronius_site_power')|float / 1000)|round(2) }}
    energy_cost_today:
      friendly_name: Energy Cost Today
      icon_template: mdi:currency-usd
      entity_id: input_number.energy_cost_today
      unit_of_measurement: $
      value_template: >-
        {{ (states('input_number.energy_cost_today')|float)|round(2) }}
    energy_exported_today:
      friendly_name: Energy exported Today
      icon_template: mdi:flash
      entity_id: input_number.energy_exported_today
      unit_of_measurement: kWh
      value_template: >-
        {{ (states('input_number.energy_exported_today')|float / 1000)|round(2) }}
    energy_imported_peak_today:
      friendly_name: Energy Imported Peak Today
      icon_template: mdi:flash
      entity_id: input_number.energy_imported_peak_today
      unit_of_measurement: kWh
      value_template: >-
        {{ (states('input_number.energy_imported_peak_today')|float / 1000)|round(2) }}
    energy_imported_shoulder_today:
      friendly_name: Energy Imported Shoulder Today
      icon_template: mdi:flash
      entity_id: input_number.energy_imported_shoulder_today
      unit_of_measurement: kWh
      value_template: >-
        {{ (states('input_number.energy_imported_shoulder_today')|float / 1000)|round(2) }}
    energy_imported_offpeak_today:
      friendly_name: Energy Imported Off-Peak Today
      icon_template: mdi:flash
      entity_id: input_number.energy_imported_offpeak_today
      unit_of_measurement: kWh
      value_template: >-
        {{ (states('input_number.energy_imported_offpeak_today')|float / 1000)|round(2) }}
