- platform: template
  sensors:
    garage_roller_door:
      friendly_name: "Garage Roller Door"
      entity_id:
        binary_sensor.door_window_sensor_158d0002045498
        binary_sensor.door_window_sensor_158d000205b28a
      value_template: >-
        {% if states.binary_sensor.door_window_sensor_158d0002045498.state == 'off' %}
          Closed
        {% elif states.binary_sensor.door_window_sensor_158d000205b28a.state == 'off' %}
          Open
        {% elif states.binary_sensor.door_window_sensor_158d0002045498.state == 'on' and
        states.binary_sensor.door_window_sensor_158d000205b28a.state == 'on' %}
          Moving
        {% else %}
          Unknown
        {% endif %}
      icon_template: >-
        {% if states.binary_sensor.door_window_sensor_158d0002045498.state == 'off' %}
          mdi:garage
        {% elif states.binary_sensor.door_window_sensor_158d000205b28a.state == 'off' %}
          mdi:garage-open
        {% elif states.binary_sensor.door_window_sensor_158d0002045498.state == 'on' and
        states.binary_sensor.door_window_sensor_158d000205b28a.state == 'on' %}
          mdi:garage-alert
        {% else %}
          mdi:help
        {% endif %}
