- platform: template
  sensors:
    washing_machine_door:
      friendly_name: "Washing Machine Door"
      icon_template: mdi:washing-machine
      entity_id: binary_sensor.door_window_sensor_158d00020b5331
      value_template: >-
        {% if states.binary_sensor.door_window_sensor_158d00020b5331.state == 'on' %}
          Open
        {% elif states.binary_sensor.door_window_sensor_158d00020b5331.state == 'off' %}
          Closed
        {% else %}
          n/a
        {% endif %}
