dave_asleep:
  name: Is Dave asleep?
rae_asleep:
  name: Is Rae asleep?

guest_mode:
  name: Guest Mode
  icon: mdi:account-plus

#PIRs
kitchen_pir_enable:
  name: Enable Kitchen PIR
  icon: mdi:run-fast
family_pir_enable:
  name: Enable Family PIR
  icon: mdi:run-fast
lounge_pir_enable:
  name: Enable Lounge PIR
  icon: mdi:run-fast

#Bedside lamps
dave_bedside_auto:
  name: Automatic Evening Dave Bedside
  icon: mdi:lamp
rae_bedside_auto:
  name: Automatic Evening Rae Bedside
  icon: mdi:lamp

#garage lighting
garage_lights_door_auto:
  name: Automatic garage lighting (Doors)
  icon: mdi:door

#github auto pull
config_auto_update:
  name: Config Auto Update
  icon: mdi:download

#restart after config download
config_auto_restart:
  name: Restart After Config Update
  icon: mdi:restart
